import Head from "next/head";
import { motion as m } from "framer-motion";

export default function Home() {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      className="text-gray-900 absolute top-0 left-0 w-full h-full bg-beige"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className="mt-40 p-10 overflow-hidden border-b border-black">
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "60%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-9xl font-myTupiBold"
          >
            JAMIE HUGHES
          </m.h1>
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-6xl font-myTupiBold"
          >
            FRONT END DEVELOPER
          </m.h1>

          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-6xl font-myTupiBold "
          >
            UI DESIGNER
          </m.h1>
        </div>
        <div className="p-10">
          <div className="font-myTupi grid grid-cols-2 gap-4 mt-8">
            <div className="col-span-1">
              <div className="font-myTupiBold text-6xl uppercase">ABOUT:</div>
              <div className="font-myTupi text-1xl pr-10 ">
                Hi, I am Jamie, a front-end developer and web designer based in
                Christchurch, New Zealand. With 2 years of experience, I
                specialize in creating responsive and user-friendly websites. I
                have a strong passion for design and love creating websites that
                provide great user experiences. If you are looking for a
                stunning website or custom web application, please feel free to
                browse my portfolio and get in touch to discuss your project.
              </div>
              <div className="font-myTupiBold text-6xl uppercase pt-10">
                SKILLS:
              </div>
              <div className="font-myTupi text-1xl pr-10 ">
                Hi, I am Jamie, a front-end developer and web designer based in
                Christchurch, New Zealand. With 2 years of experience, I
                specialize in creating responsive and user-friendly websites. I
                have a strong passion for design and love creating websites that
                provide great user experiences. If you are looking for a
                stunning website or custom web application, please feel free to
                browse my portfolio and get in touch to discuss your project.
              </div>
            </div>

            <div className="col-span-1  items-center">
              <div className="font-myTupiBold text-6xl uppercase ">SKILLS:</div>
              <div className="font-myTupi text-1xl pr-10 ">
                Hi, I am Jamie, a front-end developer and web designer based in
                Christchurch, New Zealand. With 2 years of experience, I
                specialize in creating responsive and user-friendly websites. I
                have a strong passion for design and love creating websites that
                provide great user experiences. If you are looking for a
                stunning website or custom web application, please feel free to
                browse my portfolio and get in touch to discuss your project.
              </div>
            </div>
          </div>
        </div>
      </main>
    </m.div>
  );
}
